# Generated by Django 3.2.5 on 2021-08-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Release',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
