# Generated by Django 3.2.5 on 2021-08-17 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tv', '0002_alter_book_release'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Show',
        ),
    ]
